### PR TITLE
Add support for Grid 12.1.0.2 and use versioncmp

### PR DESCRIPTION
**Pull request by carroarmato0**
Added the grid response file for 12.1.0.2

Using versioncmp to simplify version comparisons, at least for installasm

Signed-off-by: Christophe Vanlancker <christophe.vanlancker@inuits.eu>

### CODE REVIEW

**Comment by biemond** [comment]
Thanks,

really appreciated

**Comment by carroarmato0** [comment]
If you want you can play around with the versioncmp function and add it to the other classes which require a version comparison in the strings :)

**Comment by biemond** [comment]
yeah cool I saw that. is it a stdlib function?

**Comment by carroarmato0** [comment]
It has been incorportated in puppet since at least 0.24.8

**Comment by biemond** [comment]
oh man :+1:  hehe

**Comment by carroarmato0** [comment]
Ah oeps, forgot to update the spec files accordingly with the bump in supported Grid release

**Comment by carroarmato0** [comment]
I just realized I made a silly mistake when re-checking the code I submitted,  versioncmp  needs 2 parameters to compare with.  The pull request I submitted compares the version string with nothing instead of comparing it against  $version,  so ofcourse the end result with always be >=0.

**Pull request merged**
