### PR TITLE
db_control] Initial refacter with support for multiple providers

### PR DESCRIPTION
**Pull request by hajee**
Also fix the problems with refreshonly. This PR is the base for adding a provider to control a database controlled by grid

### CODE REVIEW

**Comment by biemond** [comment]
Do I need this byebug require on lib/puppet/type/db_control.rb?

**Comment by hajee** [comment]
No. IThat is a residue from development. I'm now working on the srvctl provder for ASM. I'll remove it in that PR.

**Comment by biemond** [comment]
and this error 

==> soadb: Notice: /Stage[main]/Oradb_12c/Oradb::Listener[start listener]/Db_listener[start listener]/ensure: ensure changed 'stop' to 'start'
==> soadb: Error: Could not set 'start' on ensure: undefined local variable or method `debugger' for #<Puppet::Type::Db_control::ProviderNogrid:0x7f072019be18> at 19:/tmp/vagrant-puppet/modules-e130052d73d3d620104b72a4a92d8aa8/oradb/manifests/dbactions.pp
==> soadb: Error: Could not set 'start' on ensure: undefined local variable or method `debugger' for #<Puppet::Type::Db_control::ProviderNogrid:0x7f072019be18> at 19:/tmp/vagrant-puppet/modules-e130052d73d3d620104b72a4a92d8aa8/oradb/manifests/dbactions.pp
==> soadb: Wrapped exception:
==> soadb: undefined local variable or method `debugger' for #<Puppet::Type::Db_control::ProviderNogrid:0x7f072019be18>
==> soadb: Error: /Stage[main]/Oradb_12c/Oradb::Dbactions[start oraDb]/Db_control[instance control start oraDb]/ensure: change from stop to start failed: Could not set 'start' on ensure: undefined local variable or method `debugger' for #<Puppet::Type::Db_control::ProviderNogrid:0x7f072019be18> at 19:/tmp/vagrant-puppet/modules-e130052d73d3d620104b72a4a92d8aa8/oradb/manifests/dbactions.pp
==> soadb: Notice: /Stage[main]/Oradb_12c/Oradb::Autostartdatabase[autostart oracle]/Exec[set dbora soarepos:/oracle/product/12.1/db]: Dependency Db_control[instance control start oraDb] has failures: true
==> soadb: Warning: /Stage[main]/Oradb_12c/Oradb::Autostartdatabase[autos

**Comment by hajee** [comment]
Like I said. There is still a debgger statement left. PR #84 fixes this. Allong with adding an other provider

**Comment by biemond** [comment]
Can you explain all the use cases of db_control which it now can handle and what was not working before.

**Comment by biemond** [comment]
I was expecting this will shutdown everything,  a DB on ASM

    db_control{'instance control db':
      ensure                  => 'stop',
      instance_name           => hiera('oracle_database_name'),
      oracle_product_home_dir => hiera('oracle_home_dir'),
      os_user                 => hiera('oracle_os_user'),
      require                 => Oradb::Database['oraDb'],
    }

    db_control{'instance control asm':
      ensure                  => 'stop',
      instance_name           => '+ASM',
      oracle_product_home_dir => hiera('oracle_home_dir'),
      grid_product_home_dir   => hiera('grid_home_dir'),
      os_user                 => hiera('grid_os_user'),
      db_type                 => 'asm',
      require                 => Db_control["instance control db"],
    }

it looks like for ASM or grid this statement is not correct or I did something wrong.

/bin/ps -ef | /bin/grep -v grep | /bin/grep 'ora_smon_+ASM'

it should be asm_smon instead of ora_smon,

/bin/ps -ef | /bin/grep -v grep | /bin/grep 'asm_smon_+ASM'
grid     10499     1  0 15:33 ?        00:00:00 asm_smon_+ASM

also changing it to asm didn't work.

**Comment by hajee** [comment]
You must specify the provider. By default it will take `sqlplus`.

```
db_control{'instance control db':
  ensure                  => 'stop',
  instance_name           => hiera('oracle_database_name'),
  oracle_product_home_dir => hiera('oracle_home_dir'),
  os_user                 => hiera('oracle_os_user'),
  provider                => 'srvctl',
  require                 => Oradb::Database['oraDb'],
}
```

**Comment by biemond** [comment]
Ok what does db type parameter do then , this should do this for me, asm or grid is not working with sqlplus

**Comment by hajee** [comment]
It only changes function when used with the `srvctl`  provider. We zould do a check in the type for that.

**Comment by biemond** [comment]
with an export of ORACLE_HOME it is working

==> dbasm: Debug: instance_status ORACLE_HOME=/app/oracle/product/11.2/db;export PATH=/app/oracle/product/11.2/db/bin:$PATH;export LD_LIBRARY_PATH=/app/oracle/product/11.2/db/lib;$ORACLE_HOME/bin/srvctl status asm
==> dbasm: Debug: ****ORACLE_HOME environment variable is not set.
==> dbasm:     ORACLE_HOME should be set to the main
==> dbasm:     directory that contains Oracle products.
==> dbasm:     Set and export ORACLE_HOME, then re-run.
==> dbasm:


==> dbasm: Debug: instance_status export ORACLE_HOME=/app/oracle/product/11.2/db;export PATH=/app/oracle/product/11.2/db/bin:$PATH;export LD_LIBRARY_PATH=/app/oracle/product/11.2/db/lib;$ORACLE_HOME/bin/srvctl status asm
==> dbasm: Debug: ASM is running on dbasm
==> dbasm:
==> dbasm: Debug: instance action: stop on instance type asm
==> dbasm: Debug: instance_status export ORACLE_HOME=/app/oracle/product/11.2/db;export PATH=/app/oracle/product/11.2/db/bin:$PATH;export LD_LIBRARY_PATH=/app/oracle/product/11.2/db/lib;$ORACLE_HOME/bin/srvctl stop asm -f
==> dbasm: Debug:
==> dbasm: Notice: /Stage[main]/Oradb_asm/Db_control[instance control asm]/ensure: ensure changed 'start' to 'stop'
==> dbasm: Debug: /Stage[main]/Oradb_asm/Db_control[instance control asm]: The container Class[Oradb_asm] will propagate my refresh event

**Pull request merged**
