### PR TITLE
add timeout parameter for database creation

### PR DESCRIPTION
**Pull request by pmpetit**
Hello,
as discussed in issue 
https://github.com/biemond/biemond-oradb/issues/237

### CODE REVIEW

**Comment by biemond** [comment]
nice, I think you can just use 0 as param default value instead of undef and assign it to a different var.

**Comment by pmpetit** [comment]
HI,
i also prefer...
i change it
thanks





*Pierre-Marie PETIT*
SI Engineer
Tech & Talents - B'TWIN

*+33 6 48 26 78 93Check our new
website: https://techandtalents.subsidia.org/
<https://techandtalents.subsidia.org/>*

**Comment by biemond** [comment]
can you fix the error on line 322 , it is still using the old param which does not exists anymore

**Comment by pmpetit** [comment]
ooops !
sorry about that....




*Pierre-Marie PETIT*
SI Engineer
Tech & Talents - B'TWIN

*+33 6 48 26 78 93Check our new
website: https://techandtalents.subsidia.org/
<https://techandtalents.subsidia.org/>*

**Comment by pmpetit** [comment]
Done




*Pierre-Marie PETIT*
SI Engineer
Tech & Talents - B'TWIN

*+33 6 48 26 78 93Check our new
website: https://techandtalents.subsidia.org/
<https://techandtalents.subsidia.org/>*

**Pull request merged**
