### PR TITLE
Added logic for dbora for auto start

### PR DESCRIPTION
**Pull request by ssubr06**
shell type as a option for autostart manifests and modified .epp file for dbora_Linux.epp dbora_Sunos.epp

### CODE REVIEW

**Comment by ssubr06** [comment]
@biemond ..I am not sure why the test failing as it looking for some files ? I have added an new parameter to pass through the autostartdatabase.pp.. can you check and let me know

**Comment by ssubr06** [comment]
@biemond , Do you know why coverage/coveralls  — Coverage pending from Coveralls.io  ? I am new here and can you help to get through this error

**Comment by biemond** [comment]
Nice it looks good to me

**Comment by ssubr06** [comment]
@biemond Thanks.. so what is the next step to get this new changes in my oradb module? I still see some checks pending..

**Pull request merged**
