### PR TITLE
template/db_client_12.1.0.2.rsp.erb: remove invalid contents.

### PR DESCRIPTION
**Pull request by surcouf**
Hi,

Some directives are invalid in provided template to install Oracle DB client 12.1.0.2 :

    PROXY_REALM,
    PROXY_HOST,
    PROXY_PORT,
    PROXY_USER,
    PROXY_PWD,
    AUTOUPDATES_MYORACLESUPPORT_USERNAME,
    AUTOUPDATES_MYORACLESUPPORT_PASSWORD,
    oracle.installer.autoupdates.option,
    oracle.installer.autoupdates.downloadUpdatesLoc.

This PR removes theses directives.

Regards,

Raphaël SurcouF.

### CODE REVIEW

**Comment by biemond** [comment]
thanks a lot,

Did you get an error or are these warnings. I think I tested this client install but I will retest it.

thanks

**Comment by surcouf** [comment]
Hi, 

 I'm getting this error : 

```
Notice: oradb::installdb /opt/oracle/client/12.1.0.2 does not exists
Notice: /Stage[main]/Profile::Oracle::Client/Oradb::Client[client-12.1.0.2]/Notify[oradb::installdb /opt/oracle/client/12.1.0.2 does not exists]/message: defined 'message' as 'oradb::installdb /opt/oracle/client/12.1.0.2 does not exists'
Notice: /Stage[main]/Profile::Oracle::Client/Oradb::Client[client-12.1.0.2]/Exec[extract /var/tmp/install/database/12.1.0.2/linux.x64_11gR2_client.zip]/returns: executed successfully
Notice: /Stage[main]/Profile::Oracle::Client/Oradb::Client[client-12.1.0.2]/Exec[install oracle client client-12.1.0.2]/returns: Starting Oracle Universal Installer...
Notice: /Stage[main]/Profile::Oracle::Client/Oradb::Client[client-12.1.0.2]/Exec[install oracle client client-12.1.0.2]/returns: 
Notice: /Stage[main]/Profile::Oracle::Client/Oradb::Client[client-12.1.0.2]/Exec[install oracle client client-12.1.0.2]/returns: Checking Temp space: must be greater than 120 MB.   Actual 573 MB    Passed
Notice: /Stage[main]/Profile::Oracle::Client/Oradb::Client[client-12.1.0.2]/Exec[install oracle client client-12.1.0.2]/returns: Checking swap space: must be greater than 150 MB.   Actual 1968 MB    Passed
Notice: /Stage[main]/Profile::Oracle::Client/Oradb::Client[client-12.1.0.2]/Exec[install oracle client client-12.1.0.2]/returns: Preparing to launch Oracle Universal Installer from /tmp/OraInstall2017-12-11_11-09-17AM. Please wait ...[FATAL] [INS-10105] The given response file /var/tmp/install/db_client_12.1.0.2.rsp is not valid.
Notice: /Stage[main]/Profile::Oracle::Client/Oradb::Client[client-12.1.0.2]/Exec[install oracle client client-12.1.0.2]/returns:    CAUSE: Syntactically incorrect response file. Either unexpected variables are specified or expected variables are not specified in the response file.
Notice: /Stage[main]/Profile::Oracle::Client/Oradb::Client[client-12.1.0.2]/Exec[install oracle client client-12.1.0.2]/returns:    ACTION: Refer the latest product specific response file template
Notice: /Stage[main]/Profile::Oracle::Client/Oradb::Client[client-12.1.0.2]/Exec[install oracle client client-12.1.0.2]/returns:    SUMMARY:
Notice: /Stage[main]/Profile::Oracle::Client/Oradb::Client[client-12.1.0.2]/Exec[install oracle client client-12.1.0.2]/returns:        - cvc-complex-type.2.4.a: Invalid content was found starting with element 'PROXY_REALM'. One of '{"":oracle.install.responseFileVersion, "":oracle.install.client.installType, "":SELECTED_LANGUAGES, "":ORACLE_HOSTNAME, "":INVENTORY_LOCATION, "":UNIX_GROUP_NAME, "":ORACLE_BASE, "":ORACLE_HOME, "":oracle.install.client.oramtsPortNumber, "":oracle.install.client.customComponents, "":oracle.install.client.schedulerAgentHostName, "":oracle.install.client.schedulerAgentPortNumber}' is expected.
Error: '/bin/sh -c 'unset DISPLAY;/var/tmp/install/client_12.1.0.2/client/runInstaller -silent -waitforcompletion -ignoreSysPrereqs -ignorePrereq -responseFile /var/tmp/install/db_client_12.1.0.2.rsp'' returned 255 instead of one of [6,0]
Error: /Stage[main]/Profile::Oracle::Client/Oradb::Client[client-12.1.0.2]/Exec[install oracle client client-12.1.0.2]/returns: change from notrun to 6 0 failed: '/bin/sh -c 'unset DISPLAY;/var/tmp/install/client_12.1.0.2/client/runInstaller -silent -waitforcompletion -ignoreSysPrereqs -ignorePrereq -responseFile /var/tmp/install/db_client_12.1.0.2.rsp'' returned 255 instead of one of [6,0]
```

Regards, 

Raphaël SurcouF.

**Comment by biemond** [comment]
thanks,

this is some general issue and in that case it is always complaining about proxy etc. there is another issue going on with this template. I will do some tests.

**Comment by biemond** [comment]
it works for me , even with these extra attributes.

```
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/File[/home/oracle/.bash_profile]/group: group changed 'oinstall' to 'dba'
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/File[/home/oracle/.bash_profile]/mode: mode changed '0644' to '0775'
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Oradb::Utils::Dborainst[oracle orainst 12.1.0.2]/File[/etc/oraInst.loc]/ensure: defined content as '{md5}0e60c51d6c306f4b09c099171747598b'
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/File[/var/tmp/install/db_client_12.1.0.2.rsp]/ensure: defined content as '{md5}4dc52fc0a888e5c1906e1ab9caf3b5c9'
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[install oracle client 12.1.0.2_Linux-x86-64]/returns: Starting Oracle Universal Installer...
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[install oracle client 12.1.0.2_Linux-x86-64]/returns:
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[install oracle client 12.1.0.2_Linux-x86-64]/returns: Checking Temp space: must be greater than 415 MB.   Actual 70771 MB    Passed
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[install oracle client 12.1.0.2_Linux-x86-64]/returns: Checking swap space: must be greater than 150 MB.   Actual 5999 MB    Passed
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[install oracle client 12.1.0.2_Linux-x86-64]/returns: Preparing to launch Oracle Universal Installer from /tmp/OraInstall2017-12-11_11-36-18AM. Please wait ...You can find the log of this install session at:
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[install oracle client 12.1.0.2_Linux-x86-64]/returns:  /oracle/oraInventory/logs/installActions2017-12-11_11-36-18AM.log
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[install oracle client 12.1.0.2_Linux-x86-64]/returns: The installation of Oracle Client 12c was successful.
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[install oracle client 12.1.0.2_Linux-x86-64]/returns: Please check '/oracle/oraInventory/logs/silentInstall2017-12-11_11-36-18AM.log' for more details.
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[install oracle client 12.1.0.2_Linux-x86-64]/returns: Successfully Setup Software.
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[install oracle client 12.1.0.2_Linux-x86-64]/returns: executed successfully
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[run root.sh script 12.1.0.2_Linux-x86-64]/returns: Check /oracle/product/12.1/client/install/root_dbcdb.example.com_2017-12-11_11-37-44.log for the output of root script
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[run root.sh script 12.1.0.2_Linux-x86-64]/returns: executed successfully
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/File[/var/tmp/install/netca_client_12.1.0.2.rsp]/ensure: defined content as '{md5}c1f4544ccde90f17278dee9f26692b7a'
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[install oracle net 12.1.0.2_Linux-x86-64]/returns:
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[install oracle net 12.1.0.2_Linux-x86-64]/returns: Parsing command line arguments:
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[install oracle net 12.1.0.2_Linux-x86-64]/returns:     Parameter "silent" = true
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[install oracle net 12.1.0.2_Linux-x86-64]/returns:     Parameter "responsefile" = /var/tmp/install/netca_client_12.1.0.2.rsp
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[install oracle net 12.1.0.2_Linux-x86-64]/returns: Done parsing command line arguments.
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[install oracle net 12.1.0.2_Linux-x86-64]/returns: Oracle Net Services Configuration:
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[install oracle net 12.1.0.2_Linux-x86-64]/returns: Profile configuration complete.
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[install oracle net 12.1.0.2_Linux-x86-64]/returns: Oracle Net Services configuration successful. The exit code is 0
==> dbcdb: Notice: /Stage[main]/Oradb_client/Oradb::Client[12.1.0.2_Linux-x86-64]/Exec[install oracle net 12.1.0.2_Linux-x86-64]/returns: executed successfully
```


```
[vagrant@dbcdb ~]$ cat /var/tmp/install/db_client_12.1.0.2.rsp


###############################################################################
## Copyright(c) Oracle Corporation 1998,2013. All rights reserved.           ##
##                                                                           ##
## Specify values for the variables listed below to customize                ##
## your installation.                                                        ##
##                                                                           ##
## Each variable is associated with a comment. The comment                   ##
## can help to populate the variables with the appropriate                   ##
## values.							             ##
##                                                                           ##
###############################################################################


#-------------------------------------------------------------------------------
# Do not change the following system generated value.
#-------------------------------------------------------------------------------
oracle.install.responseFileVersion=/oracle/install/rspfmt_clientinstall_response_schema_v12.1.0

#-------------------------------------------------------------------------------
# This variable holds the hostname of the system as set by the user.
# It can be used to force the installation to use an alternative
# hostname rather than using the first hostname found on the system
# (e.g., for systems with multiple hostnames and network interfaces).
#-------------------------------------------------------------------------------
ORACLE_HOSTNAME=

#-------------------------------------------------------------------------------
# Unix group to be set for the inventory directory.
#-------------------------------------------------------------------------------
UNIX_GROUP_NAME=oinstall

#-------------------------------------------------------------------------------
# Inventory location.
#-------------------------------------------------------------------------------
INVENTORY_LOCATION=/oracle/oraInventory

#-------------------------------------------------------------------------------
# Specify the languages in which the components will be installed.
#
# en   : English                  ja   : Japanese
# fr   : French                   ko   : Korean
# ar   : Arabic                   es   : Latin American Spanish
# bn   : Bengali                  lv   : Latvian
# pt_BR: Brazilian Portuguese     lt   : Lithuanian
# bg   : Bulgarian                ms   : Malay
# fr_CA: Canadian French          es_MX: Mexican Spanish
# ca   : Catalan                  no   : Norwegian
# hr   : Croatian                 pl   : Polish
# cs   : Czech                    pt   : Portuguese
# da   : Danish                   ro   : Romanian
# nl   : Dutch                    ru   : Russian
# ar_EG: Egyptian                 zh_CN: Simplified Chinese
# en_GB: English (Great Britain)  sk   : Slovak
# et   : Estonian                 sl   : Slovenian
# fi   : Finnish                  es_ES: Spanish
# de   : German                   sv   : Swedish
# el   : Greek                    th   : Thai
# iw   : Hebrew                   zh_TW: Traditional Chinese
# hu   : Hungarian                tr   : Turkish
# is   : Icelandic                uk   : Ukrainian
# in   : Indonesian               vi   : Vietnamese
# it   : Italian
#
# all_langs   : All languages
#
# Specify value as the following to select any of the languages.
# Example : SELECTED_LANGUAGES=en,fr,ja
#
# Specify value as the following to select all the languages.
# Example : SELECTED_LANGUAGES=all_langs
#-------------------------------------------------------------------------------
SELECTED_LANGUAGES=en

#-------------------------------------------------------------------------------
# Complete path of the Oracle Home
#-------------------------------------------------------------------------------
ORACLE_HOME=/oracle/product/12.1/client

#-------------------------------------------------------------------------------
# Complete path of the Oracle Base.
#-------------------------------------------------------------------------------
ORACLE_BASE=/oracle

#------------------------------------------------------------------------------
#Name       : INSTALL_TYPE
#Datatype   : String
#Description: Installation type of the component.
#
#             The following choices are available. The value should contain
#             only one of these choices.
#               - InstantClient
#               - Administrator
#               - Runtime
#               - Custom
#
#Example    : INSTALL_TYPE = Administrator
#------------------------------------------------------------------------------
oracle.install.client.installType=Administrator

#-------------------------------------------------------------------------------
# Name       : oracle.install.client.customComponents
# Datatype   : StringList
#
# This property is considered only if INSTALL_TYPE is set to "Custom"
#
# Description: List of Client Components you would like to install
#
#   The following choices are available. You may specify any
#   combination of these choices.  The components you choose should
#   be specified in the form "internal-component-name:version"
#   Below is a list of components you may specify to install.
#
# oracle.sqlj:12.1.0.1.0 -- "Oracle SQLJ"
# oracle.rdbms.util:12.1.0.1.0 -- "Oracle Database Utilities"
# oracle.javavm.client:12.1.0.1.0 -- "Oracle Java Client"
# oracle.sqlplus:12.1.0.1.0 -- "SQL*Plus"
# oracle.dbjava.jdbc:12.1.0.1.0 -- "Oracle JDBC/THIN Interfaces"
# oracle.ldap.client:12.1.0.1.0 -- "Oracle Internet Directory Client"
# oracle.rdbms.oci:12.1.0.1.0 -- "Oracle Call Interface (OCI)"
# oracle.precomp:12.1.0.1.0 -- "Oracle Programmer"
# oracle.xdk:12.1.0.1.0 -- "Oracle XML Development Kit"
# oracle.network.aso:12.1.0.1.0 -- "Oracle Advanced Security"
# oracle.oraolap.mgmt:12.1.0.1.0 -- "OLAP Analytic Workspace Manager and Worksheet"
# oracle.network.client:12.1.0.1.0 -- "Oracle Net"
# oracle.network.cman:12.1.0.1.0 -- "Oracle Connection Manager"
# oracle.network.listener:12.1.0.1.0 -- "Oracle Net Listener"
# oracle.ordim.client:12.1.0.1.0 -- "Oracle Multimedia Client Option"
# oracle.odbc:12.1.0.1.0 -- "Oracle ODBC Driver"
# oracle.has.client:12.1.0.1.0 -- "Oracle Clusterware High Availability API"
# oracle.dbdev:12.1.0.1.0 -- "Oracle SQL Developer"
# oracle.rdbms.scheduler:12.1.0.1.0 -- "Oracle Scheduler Agent"
#
# Example    : oracle.install.client.customComponents="oracle.precomp:12.1.0.1.0","oracle.oraolap.mgmt:12.1.0.1.0","oracle.rdbms.scheduler:12.1.0.1.0"
#-------------------------------------------------------------------------------
oracle.install.client.customComponents=

#-------------------------------------------------------------------------------
# Host name to be used for by the Oracle Scheduler Agent.
# This needs to be entered in case oracle.rdbms.scheduler is selected in the
# list of custom components during custom install
#
# Example    : oracle.install.client.schedulerAgentHostName = acme.domain.com
#------------------------------------------------------------------------------
oracle.install.client.schedulerAgentHostName=

#------------------------------------------------------------------------------
# Port number to be used for by the Oracle Scheduler Agent.
# This needs to be entered in case oracle.rdbms.scheduler is selected in the
# list of custom components during custom install
#
# Example: oracle.install.client.schedulerAgentPortNumber = 1500
#------------------------------------------------------------------------------
oracle.install.client.schedulerAgentPortNumber=

#------------------------------------------------------------------------------
# Specify the auto-updates option. It can be one of the following:
#   - MYORACLESUPPORT_DOWNLOAD
#   - OFFLINE_UPDATES
#   - SKIP_UPDATES
#------------------------------------------------------------------------------
oracle.installer.autoupdates.option=SKIP_UPDATES

#------------------------------------------------------------------------------
# In case MYORACLESUPPORT_DOWNLOAD option is chosen, specify the location where
# the updates are to be downloaded.
# In case OFFLINE_UPDATES option is chosen, specify the location where the updates
# are present.
#------------------------------------------------------------------------------
oracle.installer.autoupdates.downloadUpdatesLoc=

#------------------------------------------------------------------------------
# Specify the My Oracle Support Account Username which has the patches download privileges
# to be used for software updates.
#  Example   : AUTOUPDATES_MYORACLESUPPORT_USERNAME=abc@oracle.com
#------------------------------------------------------------------------------
AUTOUPDATES_MYORACLESUPPORT_USERNAME=

#------------------------------------------------------------------------------
# Specify the My Oracle Support Account Username password which has the patches download privileges
# to be used for software updates.
#
# Example    : AUTOUPDATES_MYORACLESUPPORT_PASSWORD=password
#------------------------------------------------------------------------------
AUTOUPDATES_MYORACLESUPPORT_PASSWORD=

#------------------------------------------------------------------------------
# Specify the Proxy server name. Length should be greater than zero.
#
# Example    : PROXY_HOST=proxy.domain.com
#------------------------------------------------------------------------------
PROXY_HOST=

#------------------------------------------------------------------------------
# Specify the proxy port number. Should be Numeric and atleast 2 chars.
#
# Example    : PROXY_PORT=25
#------------------------------------------------------------------------------
PROXY_PORT=

#------------------------------------------------------------------------------
# Specify the proxy user name. Leave PROXY_USER and PROXY_PWD
# blank if your proxy server requires no authentication.
#
# Example    : PROXY_USER=username
#------------------------------------------------------------------------------
PROXY_USER=

#------------------------------------------------------------------------------
# Specify the proxy password. Leave PROXY_USER and PROXY_PWD
# blank if your proxy server requires no authentication.
#
# Example    : PROXY_PWD=password
#------------------------------------------------------------------------------
PROXY_PWD=

#------------------------------------------------------------------------------
# Specify the proxy realm.
#
# Example    : PROXY_REALM=metalink
#------------------------------------------------------------------------------
PROXY_REALM=
```

**Comment by surcouf** [comment]
My bad...
I've used a wrong archive file...

Sorry :-)

**Pull request closed without merging**
