### PR TITLE
update Hiera-Version

### PR DESCRIPTION
**Pull request by cocker-cc**
- fix Warning “Use of 'hiera.yaml' version 4 is deprecated. It should be converted to version 5”
- sort YAML-Files alphabetically

### CODE REVIEW

**Comment by cocker-cc** [comment]
ping  
this is important, as Deprecation-Warnings may lead to Errors with Future-Puppet-Versions

**Comment by biemond** [comment]
thank you so much

**Comment by cocker-cc** [comment]
In fact, I made a Mistake.  PR: #303

**Comment by cocker-cc** [comment]
Are you interested in having PDK updated, and having the Module linted accordingly?  
I am currently working on this.  These are many many Formatting-Changes.

**Comment by biemond** [comment]
will be very happy with this.  if it works and is better it will be very welcome.

**Pull request merged**
